document.addEventListener('DOMContentLoaded', () => {
    const audio = document.getElementById('audio');
    const lyricsContainer = document.getElementById('lyrics-container');
    let lyricsData = [];
    let activeIndex = -1;

    // Load the JSON generated by Whisper
    fetch('karaoke_data.json')
        .then(response => response.json())
        .then(data => {
            lyricsData = data.segments;
            renderLyrics();
        })
        .catch(err => {
            console.error('Failed to load karaoke_data.json:', err);
            lyricsContainer.innerHTML = '<div class="loading">無法載入動態歌詞，請確認語音辨識是否已完成。</div>';
        });

    function renderLyrics() {
        lyricsContainer.innerHTML = '';
        lyricsData.forEach((seg, index) => {
            const div = document.createElement('div');
            div.className = 'lyric-line';
            div.id = `line-${index}`;
            div.textContent = seg.text;
            
            // Allow user to click lyric to seek audio
            div.addEventListener('click', () => {
                audio.currentTime = seg.start;
                audio.play();
            });

            lyricsContainer.appendChild(div);
        });
    }

    // Update active lyric based on audio time
    audio.addEventListener('timeupdate', () => {
        const currentTime = audio.currentTime;
        let newActiveIndex = -1;

        // Find the segment that matches the current time
        for (let i = 0; i < lyricsData.length; i++) {
            const seg = lyricsData[i];
            if (currentTime >= seg.start && currentTime <= seg.end) {
                newActiveIndex = i;
                break;
            }
        }

        // If we are between segments, keep the previous active segment highlighted
        // until the next one starts, or un-highlight if it's a long pause.
        if (newActiveIndex === -1) {
            for (let i = 0; i < lyricsData.length; i++) {
                if (currentTime < lyricsData[i].start) {
                    newActiveIndex = i - 1;
                    break;
                }
            }
            if (newActiveIndex === -1 && currentTime >= lyricsData[lyricsData.length - 1]?.end) {
                newActiveIndex = lyricsData.length - 1;
            }
        }

        if (newActiveIndex !== activeIndex && newActiveIndex >= 0) {
            // Remove active class from old
            if (activeIndex !== -1) {
                const oldEl = document.getElementById(`line-${activeIndex}`);
                if (oldEl) {
                    oldEl.classList.remove('active');
                    oldEl.classList.add('past');
                }
            }

            // Add active class to new
            const newEl = document.getElementById(`line-${newActiveIndex}`);
            if (newEl) {
                newEl.classList.add('active');
                newEl.classList.remove('past');
                
                // Scroll container to center the active line
                const wrapperHeight = document.getElementById('lyrics-wrapper').offsetHeight;
                const offset = newEl.offsetTop - (wrapperHeight / 2) + (newEl.offsetHeight / 2);
                lyricsContainer.style.transform = `translateY(-${offset}px)`;
            }

            activeIndex = newActiveIndex;
        }
    });
});
